# Generated by Django 3.2.5 on 2021-07-22 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField(null=True)),
                ('telegram', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(default='')),
                ('status', models.TextField(choices=[('OPEN', 'Открыта'), ('CLOSED', 'Закрыта'), ('IN WORK', 'В работе')], default='OPEN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='request', to='requestsapi.customers')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='request', to='requestsapi.staff')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
            },
        ),
    ]
